[package]
name = "cop"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.10.2"

[[bin]]
name = "cell_test"
path = "src/bin/cell_test.rs"

[[bin]]
name = "spreadsheet_test"
path = "src/bin/spreadsheet_test.rs"