name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y libfontconfig1-dev pkg-config
    # - name: Build
    #   run: cargo build --verbose
    - name: Run Sheet tests
      run: cargo run --package cop --bin spreadsheet_test 
    - name: Run Cell tests
      run: cargo run --package cop --bin cell_test
    - name : Saving Sheet
      run: cargo run --package cop --bin saving_test
    - name: Check formatting
      run: cargo fmt -- --check
    - name: Clippy 
      run: cargo clippy --all-targets --all-features
    
