[package]
name = "actix-spreadsheet"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
bincode = "1.3"
flate2 = "1.0"
regex = "1.5"
rfd = "0.10"